name: flutter_contacts_example
description: Demonstrates how to use the flutter_contacts plugin.
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts:
    path: ../

dev_dependencies:
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
